controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - base_to_shoulder
      - shoulder_to_upper_arm
      - elbow
      - wrist
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.01
      base_to_shoulder:
        trajectory: 0.05
        goal: 0.02
      shoulder_to_upper_arm:
        trajectory: 0.05
        goal: 0.02
      elbow:
        trajectory: 0.05
        goal: 0.02
      wrist:
        trajectory: 0.05
        goal: 0.02
