<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="smore_bot">

  <xacro:include filename="$(find smore_bot_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find smore_bot_description)/urdf/smore_bot.gazebo" />

  <xacro:property name="base_radius" value="0.1" />
  <xacro:property name="base_height" value="0.05" />
  <xacro:property name="shoulder_height" value="0.1" />
  <xacro:property name="upper_arm_length" value="0.4" />
  <xacro:property name="forearm_length" value="0.3" />
  <xacro:property name="wrist_length" value="0.1" />
  <xacro:property name="joint_damping" value="0.1" />
  <xacro:property name="joint_friction" value="0.1" />

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Joint: Base to Shoulder -->
  <joint name="base_to_shoulder" type="revolute">
    <parent link="base_link"/>
    <child link="shoulder_link"/>
    <origin xyz="0 0 ${base_height/2 + shoulder_height/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="100" velocity="1.0"/>
    <dynamics damping="${joint_damping}" friction="${joint_friction}"/>
  </joint>

  <!-- Shoulder Link -->
  <link name="shoulder_link">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="${shoulder_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="${shoulder_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Joint: Shoulder to Upper Arm -->
  <joint name="shoulder_to_upper_arm" type="revolute">
    <parent link="shoulder_link"/>
    <child link="upper_arm_link"/>
    <origin xyz="0 0 ${shoulder_height/2}" rpy="1.57 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="100" velocity="1.0"/>
    <dynamics damping="${joint_damping}" friction="${joint_friction}"/>
  </joint>

  <!-- Upper Arm Link -->
  <link name="upper_arm_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 ${upper_arm_length}"/>
      </geometry>
      <origin xyz="0 0 ${upper_arm_length/2}" rpy="0 0 0"/>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 ${upper_arm_length}"/>
      </geometry>
      <origin xyz="0 0 ${upper_arm_length/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <origin xyz="0 0 ${upper_arm_length/2}" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Joint: Upper Arm to Forearm -->
  <joint name="elbow" type="revolute">
    <parent link="upper_arm_link"/>
    <child link="forearm_link"/>
    <origin xyz="0 0 ${upper_arm_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="100" velocity="1.0"/>
    <dynamics damping="${joint_damping}" friction="${joint_friction}"/>
  </joint>

  <!-- Forearm Link -->
  <link name="forearm_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 ${forearm_length}"/>
      </geometry>
      <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0"/>
      <material name="green"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 ${forearm_length}"/>
      </geometry>
      <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.4"/>
      <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Wrist Joint -->
  <joint name="wrist" type="revolute">
    <parent link="forearm_link"/>
    <child link="wrist_link"/>
    <origin xyz="0 0 ${forearm_length}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="50" velocity="1.0"/>
    <dynamics damping="${joint_damping}" friction="${joint_friction}"/>
  </joint>

  <!-- Wrist Link -->
  <link name="wrist_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 ${wrist_length}"/>
      </geometry>
      <origin xyz="0 0 ${wrist_length/2}" rpy="0 0 0"/>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 ${wrist_length}"/>
      </geometry>
      <origin xyz="0 0 ${wrist_length/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 ${wrist_length/2}" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- End Effector Joint -->
  <joint name="end_effector_joint" type="fixed">
    <parent link="wrist_link"/>
    <child link="end_effector_link"/>
    <origin xyz="0 0 ${wrist_length}" rpy="0 0 0"/>
  </joint>

  <!-- End Effector Link -->
  <link name="end_effector_link">
    <visual>
      <geometry>
        <sphere radius="0.01"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <!-- ROS2 Control interface -->
  <ros2_control name="GazeboSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>

    <joint name="base_to_shoulder">
      <command_interface name="position">
        <param name="min">-3.14</param>
        <param name="max">3.14</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="shoulder_to_upper_arm">
      <command_interface name="position">
        <param name="min">-1.57</param>
        <param name="max">1.57</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="elbow">
      <command_interface name="position">
        <param name="min">-1.57</param>
        <param name="max">1.57</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="wrist">
      <command_interface name="position">
        <param name="min">-3.14</param>
        <param name="max">3.14</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

</robot>
